### ISSUE TITLE
Uncaught Exception - System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by laurinkeithdavis** [Badgerati/NotifyMeCI#13]
Application was working fine, then suddenly it started crashing unless I set it to Run As Administrator. Otherwise, I get this error:

Application: NotifyMeCI.GUI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.Security.AccessControl.Win32.SetSecurityInfo(System.Security.AccessControl.ResourceType, System.String, System.Runtime.InteropServices.SafeHandle, System.Security.AccessControl.SecurityInfos, System.Security.Principal.SecurityIdentifier, System.Security.Principal.SecurityIdentifier, System.Security.AccessControl.GenericAcl, System.Security.AccessControl.GenericAcl)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(System.String, System.Runtime.InteropServices.SafeHandle, System.Security.AccessControl.AccessControlSections, System.Object)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(System.String, System.Security.AccessControl.AccessControlSections, System.Object)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(System.String, System.Security.AccessControl.AccessControlSections)
   at System.Security.AccessControl.FileSystemSecurity.Persist(System.String)
   at System.IO.Directory.SetAccessControl(System.String, System.Security.AccessControl.DirectorySecurity)
   at Icarus.Core.IcarusDataStore..ctor(System.String, System.String, Boolean)
   at Icarus.Core.IcarusClient.GetDataStore(System.String)
   at NotifyMeCI.Engine.Repositories.CIServerRepository.All()
   at NotifyMeCI.GUI.Form1.SetupServerList()
   at NotifyMeCI.GUI.Form1..ctor()
   at NotifyMeCI.GUI.Program.Main()

**Comment by Badgerati** [comment]
@laurin1 Looking at the stack trace I think I can tell, but would you be able to tell me which version this is occurring on?

Thanks.

**Comment by laurinkeithdavis** [comment]
1.1.1.3

**Comment by Badgerati** [comment]
Thought as much, thanks. I'll look into a fix for it.

**Comment by Badgerati** [comment]
I was able to reproduce the issue, and managed to get a fix to work locally.

The main cause of this issue was in another package I'd wrote called Icarus. I've applied the main fix in there, as it really shouldn't have been completely falling over if it had issues with permissions.

I've updated the package in NotifyMeCI for Icarus, and also applied a very minor fix for when Icarus is called.

The fix is in branch `Issue-13`. I'm assuming you're installing this via Chocolatey? If so, and you wish to test the fix, you'll need to build the solution for the DLLs. Then you can manually overwrite the `Icarus.Core.dll` and `NotifyMeCI.Engine.dll` in `C:\ProgramData\Chocolatey\lib\notify-me-ci\tools` with the newly built ones. With this, you should then be able to open NotifyMeCI as normal.

If you're all right with this fix, let me know and I can get the proper release out :)

**Comment by laurinkeithdavis** [comment]
I don't have time to configure and build this project right now. I'm running it as admin as a workaround.
